spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ''
    url: ''
    username: ''
  redis:
    primary:
      database: ''
      host: ''
      password: ''
      port: ''
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
